apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostap-site-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostap-site
  template:
    metadata:
      labels:
        app: ostap-site
    spec:
      containers:
      - name: ostap-site
        image: lolgg/ostap-site-hub:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ostap-site-service
spec:
  selector:
    app: ostap-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

