# Generated by Django 3.2.2 on 2021-05-10 18:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Назва')),
                ('amount', models.PositiveIntegerField(verbose_name='Кількість')),
                ('size', models.CharField(max_length=45, verbose_name='Розмір')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна')),
                ('state', models.CharField(choices=[('preparing', 'Підготовка'), ('in_process', 'В процесі'), ('complete', 'Готово')], max_length=10, verbose_name='Стан')),
                ('image', models.ImageField(default='default.jpg', upload_to='', verbose_name='Зображення')),
            ],
        ),
        migrations.CreateModel(
            name='Jeweller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIB', models.CharField(max_length=90, verbose_name='ПІБ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='UsedMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, verbose_name='Тип')),
                ('name', models.CharField(max_length=45, verbose_name='Назва')),
                ('amount', models.PositiveIntegerField(verbose_name='Кількість')),
                ('fk_completed_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.completedproduct', verbose_name='Готовий товар')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIB', models.CharField(max_length=90, verbose_name='ПІБ')),
                ('phone_number', models.CharField(max_length=45, verbose_name='Номер телефону')),
                ('address', models.CharField(max_length=90, verbose_name='Адреса')),
                ('type_of_jewellery', models.CharField(max_length=45, verbose_name='Тип прикраси')),
                ('delivery', models.CharField(choices=[('yes', 'Так'), ('no', 'Ні')], max_length=3, verbose_name='Доставка')),
                ('broadcast', models.CharField(choices=[('yes', 'Так'), ('no', 'Ні')], max_length=3, verbose_name='Трансляція')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Знижка')),
                ('order_datetime', models.DateTimeField(default=datetime.datetime(2021, 5, 10, 21, 33, 29, 662946))),
                ('fk_jeweller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.jeweller', verbose_name='Ювелір')),
            ],
        ),
        migrations.AddField(
            model_name='completedproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.order'),
        ),
    ]
